// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/protos/file/file.proto

package file

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	AbsolutePath  string                 `protobuf:"bytes,2,opt,name=absolutePath,proto3" json:"absolutePath,omitempty"`
	RelativePath  string                 `protobuf:"bytes,3,opt,name=relativePath,proto3" json:"relativePath,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=sizeBytes,proto3" json:"sizeBytes,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_api_protos_file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_protos_file_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *File) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

func (x *File) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *File) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *File) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SaveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileRequest) Reset() {
	*x = SaveFileRequest{}
	mi := &file_api_protos_file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileRequest) ProtoMessage() {}

func (x *SaveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileRequest.ProtoReflect.Descriptor instead.
func (*SaveFileRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_file_file_proto_rawDescGZIP(), []int{1}
}

func (x *SaveFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type SaveFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileResponse) Reset() {
	*x = SaveFileResponse{}
	mi := &file_api_protos_file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileResponse) ProtoMessage() {}

func (x *SaveFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileResponse.ProtoReflect.Descriptor instead.
func (*SaveFileResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_file_file_proto_rawDescGZIP(), []int{2}
}

func (x *SaveFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *SaveFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_api_protos_file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_file_file_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFileRequest) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_api_protos_file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_file_file_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_api_protos_file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_file_file_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileRequest) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_api_protos_file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_file_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_api_protos_file_file_proto protoreflect.FileDescriptor

const file_api_protos_file_file_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/protos/file/file.proto\x12\x04file\"\xa6\x01\n" +
	"\x04File\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\"\n" +
	"\fabsolutePath\x18\x02 \x01(\tR\fabsolutePath\x12\"\n" +
	"\frelativePath\x18\x03 \x01(\tR\frelativePath\x12\x1c\n" +
	"\tsizeBytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x03R\tcreatedAt\"G\n" +
	"\x0fSaveFileRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\"L\n" +
	"\x10SaveFileResponse\x12\x1e\n" +
	"\x04file\x18\x01 \x01(\v2\n" +
	".file.FileR\x04file\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"3\n" +
	"\x11DeleteFileRequest\x12\x1e\n" +
	"\x04file\x18\x01 \x01(\v2\n" +
	".file.FileR\x04file\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x0eGetFileRequest\x12\x1e\n" +
	"\x04file\x18\x01 \x01(\v2\n" +
	".file.FileR\x04file\"E\n" +
	"\x0fGetFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2\x81\x02\n" +
	"\vFileService\x129\n" +
	"\bSaveFile\x12\x15.file.SaveFileRequest\x1a\x16.file.SaveFileResponse\x12?\n" +
	"\n" +
	"DeleteFile\x12\x17.file.DeleteFileRequest\x1a\x18.file.DeleteFileResponse\x12>\n" +
	"\tDeleteDir\x12\x17.file.DeleteFileRequest\x1a\x18.file.DeleteFileResponse\x126\n" +
	"\aGetFile\x12\x14.file.GetFileRequest\x1a\x15.file.GetFileResponseB!Z\x1fcode-sandbox-go/api/protos/fileb\x06proto3"

var (
	file_api_protos_file_file_proto_rawDescOnce sync.Once
	file_api_protos_file_file_proto_rawDescData []byte
)

func file_api_protos_file_file_proto_rawDescGZIP() []byte {
	file_api_protos_file_file_proto_rawDescOnce.Do(func() {
		file_api_protos_file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_file_file_proto_rawDesc), len(file_api_protos_file_file_proto_rawDesc)))
	})
	return file_api_protos_file_file_proto_rawDescData
}

var file_api_protos_file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_protos_file_file_proto_goTypes = []any{
	(*File)(nil),               // 0: file.File
	(*SaveFileRequest)(nil),    // 1: file.SaveFileRequest
	(*SaveFileResponse)(nil),   // 2: file.SaveFileResponse
	(*DeleteFileRequest)(nil),  // 3: file.DeleteFileRequest
	(*DeleteFileResponse)(nil), // 4: file.DeleteFileResponse
	(*GetFileRequest)(nil),     // 5: file.GetFileRequest
	(*GetFileResponse)(nil),    // 6: file.GetFileResponse
}
var file_api_protos_file_file_proto_depIdxs = []int32{
	0, // 0: file.SaveFileResponse.file:type_name -> file.File
	0, // 1: file.DeleteFileRequest.file:type_name -> file.File
	0, // 2: file.GetFileRequest.file:type_name -> file.File
	1, // 3: file.FileService.SaveFile:input_type -> file.SaveFileRequest
	3, // 4: file.FileService.DeleteFile:input_type -> file.DeleteFileRequest
	3, // 5: file.FileService.DeleteDir:input_type -> file.DeleteFileRequest
	5, // 6: file.FileService.GetFile:input_type -> file.GetFileRequest
	2, // 7: file.FileService.SaveFile:output_type -> file.SaveFileResponse
	4, // 8: file.FileService.DeleteFile:output_type -> file.DeleteFileResponse
	4, // 9: file.FileService.DeleteDir:output_type -> file.DeleteFileResponse
	6, // 10: file.FileService.GetFile:output_type -> file.GetFileResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_protos_file_file_proto_init() }
func file_api_protos_file_file_proto_init() {
	if File_api_protos_file_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_file_file_proto_rawDesc), len(file_api_protos_file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_file_file_proto_goTypes,
		DependencyIndexes: file_api_protos_file_file_proto_depIdxs,
		MessageInfos:      file_api_protos_file_file_proto_msgTypes,
	}.Build()
	File_api_protos_file_file_proto = out.File
	file_api_protos_file_file_proto_goTypes = nil
	file_api_protos_file_file_proto_depIdxs = nil
}
