// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/protos/judge/judge.proto

package judge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 执行状态枚举
type ExecutionStatus int32

const (
	ExecutionStatus_UNKNOWN               ExecutionStatus = 0
	ExecutionStatus_EXECUTE_SUCCESS       ExecutionStatus = 1
	ExecutionStatus_COMPILE_ERROR         ExecutionStatus = 2
	ExecutionStatus_RUNTIME_ERROR         ExecutionStatus = 3
	ExecutionStatus_TIME_LIMIT_EXCEEDED   ExecutionStatus = 4
	ExecutionStatus_MEMORY_LIMIT_EXCEEDED ExecutionStatus = 5
	ExecutionStatus_SYSTEM_ERROR          ExecutionStatus = 7
	ExecutionStatus_COMPILE_SUCCESS       ExecutionStatus = 8
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "EXECUTE_SUCCESS",
		2: "COMPILE_ERROR",
		3: "RUNTIME_ERROR",
		4: "TIME_LIMIT_EXCEEDED",
		5: "MEMORY_LIMIT_EXCEEDED",
		7: "SYSTEM_ERROR",
		8: "COMPILE_SUCCESS",
	}
	ExecutionStatus_value = map[string]int32{
		"UNKNOWN":               0,
		"EXECUTE_SUCCESS":       1,
		"COMPILE_ERROR":         2,
		"RUNTIME_ERROR":         3,
		"TIME_LIMIT_EXCEEDED":   4,
		"MEMORY_LIMIT_EXCEEDED": 5,
		"SYSTEM_ERROR":          7,
		"COMPILE_SUCCESS":       8,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protos_judge_judge_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_api_protos_judge_judge_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_protos_judge_judge_proto_rawDescGZIP(), []int{0}
}

type ExecuteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	TestCase      []string               `protobuf:"bytes,3,rep,name=testCase,proto3" json:"testCase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCodeRequest) Reset() {
	*x = ExecuteCodeRequest{}
	mi := &file_api_protos_judge_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeRequest) ProtoMessage() {}

func (x *ExecuteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_judge_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_judge_judge_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecuteCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecuteCodeRequest) GetTestCase() []string {
	if x != nil {
		return x.TestCase
	}
	return nil
}

type ExecuteCodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestCaseResult []string               `protobuf:"bytes,1,rep,name=testCaseResult,proto3" json:"testCaseResult,omitempty"`
	ExecuteInfo    []*ExecutionInfo       `protobuf:"bytes,2,rep,name=executeInfo,proto3" json:"executeInfo,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteCodeResponse) Reset() {
	*x = ExecuteCodeResponse{}
	mi := &file_api_protos_judge_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCodeResponse) ProtoMessage() {}

func (x *ExecuteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_judge_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCodeResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_judge_judge_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteCodeResponse) GetTestCaseResult() []string {
	if x != nil {
		return x.TestCaseResult
	}
	return nil
}

func (x *ExecuteCodeResponse) GetExecuteInfo() []*ExecutionInfo {
	if x != nil {
		return x.ExecuteInfo
	}
	return nil
}

// 执行信息
type ExecutionInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Stdout              string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr              string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode            int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExecutionTimeUsedMs int64                  `protobuf:"varint,4,opt,name=execution_time_used_ms,json=executionTimeUsedMs,proto3" json:"execution_time_used_ms,omitempty"`
	MemoryUsedKb        int64                  `protobuf:"varint,5,opt,name=memory_used_kb,json=memoryUsedKb,proto3" json:"memory_used_kb,omitempty"`
	Status              ExecutionStatus        `protobuf:"varint,6,opt,name=status,proto3,enum=judge.ExecutionStatus" json:"status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecutionInfo) Reset() {
	*x = ExecutionInfo{}
	mi := &file_api_protos_judge_judge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionInfo) ProtoMessage() {}

func (x *ExecutionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_judge_judge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionInfo.ProtoReflect.Descriptor instead.
func (*ExecutionInfo) Descriptor() ([]byte, []int) {
	return file_api_protos_judge_judge_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionInfo) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecutionInfo) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecutionInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecutionInfo) GetExecutionTimeUsedMs() int64 {
	if x != nil {
		return x.ExecutionTimeUsedMs
	}
	return 0
}

func (x *ExecutionInfo) GetMemoryUsedKb() int64 {
	if x != nil {
		return x.MemoryUsedKb
	}
	return 0
}

func (x *ExecutionInfo) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_UNKNOWN
}

var File_api_protos_judge_judge_proto protoreflect.FileDescriptor

const file_api_protos_judge_judge_proto_rawDesc = "" +
	"\n" +
	"\x1capi/protos/judge/judge.proto\x12\x05judge\"`\n" +
	"\x12ExecuteCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1a\n" +
	"\btestCase\x18\x03 \x03(\tR\btestCase\"u\n" +
	"\x13ExecuteCodeResponse\x12&\n" +
	"\x0etestCaseResult\x18\x01 \x03(\tR\x0etestCaseResult\x126\n" +
	"\vexecuteInfo\x18\x02 \x03(\v2\x14.judge.ExecutionInfoR\vexecuteInfo\"\xe7\x01\n" +
	"\rExecutionInfo\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x123\n" +
	"\x16execution_time_used_ms\x18\x04 \x01(\x03R\x13executionTimeUsedMs\x12$\n" +
	"\x0ememory_used_kb\x18\x05 \x01(\x03R\fmemoryUsedKb\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.judge.ExecutionStatusR\x06status*\xb4\x01\n" +
	"\x0fExecutionStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fEXECUTE_SUCCESS\x10\x01\x12\x11\n" +
	"\rCOMPILE_ERROR\x10\x02\x12\x11\n" +
	"\rRUNTIME_ERROR\x10\x03\x12\x17\n" +
	"\x13TIME_LIMIT_EXCEEDED\x10\x04\x12\x19\n" +
	"\x15MEMORY_LIMIT_EXCEEDED\x10\x05\x12\x10\n" +
	"\fSYSTEM_ERROR\x10\a\x12\x13\n" +
	"\x0fCOMPILE_SUCCESS\x10\b2O\n" +
	"\x05judge\x12F\n" +
	"\vExecuteCode\x12\x19.judge.ExecuteCodeRequest\x1a\x1a.judge.ExecuteCodeResponse\"\x00B\"Z code-sandbox-go/api/protos/judgeb\x06proto3"

var (
	file_api_protos_judge_judge_proto_rawDescOnce sync.Once
	file_api_protos_judge_judge_proto_rawDescData []byte
)

func file_api_protos_judge_judge_proto_rawDescGZIP() []byte {
	file_api_protos_judge_judge_proto_rawDescOnce.Do(func() {
		file_api_protos_judge_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_judge_judge_proto_rawDesc), len(file_api_protos_judge_judge_proto_rawDesc)))
	})
	return file_api_protos_judge_judge_proto_rawDescData
}

var file_api_protos_judge_judge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protos_judge_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_protos_judge_judge_proto_goTypes = []any{
	(ExecutionStatus)(0),        // 0: judge.ExecutionStatus
	(*ExecuteCodeRequest)(nil),  // 1: judge.ExecuteCodeRequest
	(*ExecuteCodeResponse)(nil), // 2: judge.ExecuteCodeResponse
	(*ExecutionInfo)(nil),       // 3: judge.ExecutionInfo
}
var file_api_protos_judge_judge_proto_depIdxs = []int32{
	3, // 0: judge.ExecuteCodeResponse.executeInfo:type_name -> judge.ExecutionInfo
	0, // 1: judge.ExecutionInfo.status:type_name -> judge.ExecutionStatus
	1, // 2: judge.judge.ExecuteCode:input_type -> judge.ExecuteCodeRequest
	2, // 3: judge.judge.ExecuteCode:output_type -> judge.ExecuteCodeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_protos_judge_judge_proto_init() }
func file_api_protos_judge_judge_proto_init() {
	if File_api_protos_judge_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_judge_judge_proto_rawDesc), len(file_api_protos_judge_judge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_judge_judge_proto_goTypes,
		DependencyIndexes: file_api_protos_judge_judge_proto_depIdxs,
		EnumInfos:         file_api_protos_judge_judge_proto_enumTypes,
		MessageInfos:      file_api_protos_judge_judge_proto_msgTypes,
	}.Build()
	File_api_protos_judge_judge_proto = out.File
	file_api_protos_judge_judge_proto_goTypes = nil
	file_api_protos_judge_judge_proto_depIdxs = nil
}
